export const loginTexts = {
  carouselTitles: [
    { title: "Track your health status, monitor blood sugar and blood pressure." },
    { title: "Manage medications and appointments with ease." },
    { title: "Store and share reports securely." },
    { title: "Stay informed with personalized insights." },
  ],
  sendOtpButton:           "Send verification code",
  enterOtpTitle:           "Enter 6 Digit Verification Code",
  enterOtpSubtitle:        "We have sent the code to",
  verifyButton:            "Verify",
  resendText:              "Didn't receive the verification code? ",
  resendButton:            "Resend",
  phoneNumberPlaceholder:  "Enter Phone Number",
  successMessage:          "OTP has been resent to your phone",
  failedToSendOtp:         "Failed to send OTP. Please try again.",
  invalidOtp:              "Please enter a valid 6-digit OTP",
  invalidOtp2:             "Invalid OTP. Please try again.",
  sendOtpError:            "Please enter a phone number",
  sendOtpError2:           "Please enter a valid phone number (at least 10 digits)",
  error:                   "Error",
  success:                 "Success",
};
