export const profileTexts = {
  pageTitle: "User Profile",
  fullNameLabel: "Full Name",
  emailLabel: "Email address",
  yobLabel: "Year of Birth",
  heightLabel: "Height",
  targetWeightLabel: "Target Weight (kg)",
  diagnosisYearLabel: "Diagnosis Year",
  genderLabel: "Gender",
  enterDetails: "Enter Details",
  selectGender: "Select Gender",
  male: "Male",
  female: "Female",
  saveBtn: "Save",
};
