export const registerTexts = {
  welcomeTitle:                       "Welcome",
  healthProfileSubtitle:              "Let's set up your Health Profile",
  fullNameLabel:                      "Full Name",
  fullNamePlaceholder:                "Full Name",
  yearOfBirthLabel:                   "Year of Birth",
  diagnosisYearLabel:                 "Diagnosis Year",
  genderLabel:                        "Gender",
  emailAddressLabel:                  "Email Address",
  emailAddressPlaceholder:            "Enter Email Address",
  doctorReferralCodeLabel:            "Doctor Referral Code",
  doctorReferralCodePlaceholder:      "Enter Code Here",
  consentAndPrivacyTitle:             "Consent & Privacy",
  dataCollectionConsentTitle:         "Data Collection Consent",
  dataCollectionConsentDescription:
    "I consent to the collection, storage, and processing of my personal and health data in accordance with applicable data protection regulations (GDPR, HIPAA equivalent).",
  aiAnalysisConsentTitle:             "AI Analysis Consent",
  aiAnalysisConsentDescription:
    "I consent to the use of AI and Digital Twin models for analyzing my health data and generating personalized health insights and recommendations.",
  completeSetupButton:                "Complete Setup",
  error:                              "Error",
  fillFieldsError:                    "Please fill in all fields",
  failedSaveRegistration:             "Failed to save registration details.",
  creatingProfileLoading:             "Creating your profile...",
};
