export const reminders = {
  pageTitle: 'Reminders',
  addBtn: 'Add Reminder',
  deleteConfirmTitle: 'Delete Reminder',
  deleteConfirmMessage: 'Are you sure you want to delete this reminder?',
  cancelBtn: 'Cancel',
  deleteBtn: 'Delete',
  reminderTitle: 'Reminder',
  titleLabel: 'Title',
  titlePlaceholder: 'Enter Title',
  startDateLabel: 'Start Date',
  endDateLabel: 'End Date',
  selectDatePlaceholder: 'Select Date',
  scheduledTimeTitle: 'Scheduled Time',
  saveBtn: 'Save',
  selectedDaysPrefix: 'Selected',
  noDaysSelected: 'No days selected',
  emptyState: 'No reminders found. Tap the button below to add one.',
};
