export const ROUTES = {
  root: "/",
  login: "/login",
  register: "/register",
  subscription: "/subscription",
  payment: "/payment",
  appHome:           "/(app)/home",
  appMore:           "/(app)/more",
  appProfile:        "/profile",
  appNotifications:  "/notifications",
  appSettings:       "/(app)/settings",
  appLogGlucose:     "/log-glucose",
  appHba1cTracker:   "/hba1c-tracker",
  appWeightTracker:  "/weight-tracker",
  appAddMedication:    "/add-medication",
  appLifestyleQuestions: "/lifestyle-questions",
  appReminders: "/reminders",
  appActivityTracker: "/activity-tracker",
  appMeals: "/meals",
  appAddMeal: "/add-meal",
  appMealImpact: "/meal-impact",
  appSwapMeal: "/swap-meal",
  appMealCompare: "/meal-compare",
} as const;

export const APP_PATHS = [
  "/home",
  "/trends",
  "/care-plan",
  "/chat",
  "/more",
  "/profile",
  "/notifications",
  "/settings",
  "/log-glucose",
  "/hba1c-tracker",
  "/weight-tracker",
  "/add-medication",
  "/lifestyle-questions",
  "/reminders",
  "/activity-tracker",
  "/meals",
  "/add-meal",
  "/meal-impact",
  "/swap-meal",
  "/meal-compare",
] as const;
