export const subscriptionTexts = {
  takeControlOfYourHealth: "Take Control of Your Health, Everyday",
  infoText:                "Your plan will automatically renew at the end of each billing cycle.",
  reminderText:            "You'll receive a reminder before renewal.",
  proceedButton:           "Proceed",
  error:                   "Error",
  paymentFailed:           "Payment Failed",
  paymentFailedBody:       "There was an error processing your payment. Please try again.",
  invalidSession:          "Invalid payment session. Please try again.",
  failLoadPlans:           "Failed to load subscription plans",
  selectPlan:              "Please select a plan",
  loginAgain:              "Please login again",
  failCreateSubscription:  "Failed to create subscription",
  preparingPayment:        "Preparing Payment...",
  preparingPaymentSubtitle:"Please wait while we set up your payment",
  processingPayment:       "Processing Payment",
  processingPaymentSubtitle:"Please do not close this screen",
  planLabel:               "Plan",
  amountLabel:             "Amount",
  paymentSuccessful:       "Payment Successful!",
  thankYouSubscribing:     "Thank you for subscribing",
  amountPaidLabel:         "Amount Paid",
  redirectingDashboard:    "Redirecting to dashboard...",
  tryAgainBtn:             "Try Again",
  goBackBtn:               "Go Back",
  loadingPlans:            "Loading plans...",
  missingVariantInfo:      "Selected plan is missing variant information.",
  razorpayKeyMissing:      "Razorpay API key is not configured in Remote Config.",
  subscriptionForPlanPrefix: "Subscription for ",
  appName:                 "Diabetes Care App",
  subscriptionApiFailed:   "Subscription API execution failed",
  checkoutInitiated:       "Checkout initiated successfully",
  checkoutFailed:          "Checkout failed",
  subscribedSuccessfully:  "Subscribed successfully",
  subscriptionFailed:      "Subscription failed",
  startDate:               "Start Date",
  endDate:                 "End Date",
  mySubscription:          "My Subscription",
  noSubscriptions:         "No subscriptions found.",
  viewPlans:               "View Plans",
};
