export const weightTracker = {
  pageTitle: "Weight",
  toReachGoal: "To Reach Goal",
  currentWeight: "Current Weight",
  targetWeight: "Target Weight",
  bmiTitle: "BMI",
  normalWeight: ", Normal Weight",
  historySectionTitle: "History",
  onTargetBadge: "On Target",
  addBtn: "Add Weight",
  weightLabel: "Weight",
  weightPlaceholder: "eg. 75.5",
  heightLabel: "Height",
  heightPlaceholder: "Enter Height",
  dateLabel: "Date",
  datePlaceholder: "Enter Details",
  cancelBtn: "Cancel",
  saveBtn: "Save",
  underweight: "Underweight",
  normalWeightText: "Normal Weight",
  overweight: "Overweight",
  obese1: "Obese Class I",
  obese2: "Obese Class II",
  vsText: "VS",
  kgUnit: "KG",
  kgUnitLower: "kg",
  addWeightTitle: "Add Weight",
  logWeight: "Log Weight",
};
